#------------------------------------------------------------------------------
#----------------------------- Monochrome Colorscheme -------------------------
#------------------------------------------------------------------------------
#-  Name: Monochrome Dark                                                     -
#-  Author: Holairs                                                           -
#-  Colorscheme based on the Nemesis art cover from the Isaac Asimov's        -
#-  "Nemesis" book. It's a dark colorscheme with a dark background and        -
#-  bright colors for the syntax. The colors represent the hues of the        -
#-  stars depicted on the cover of the book, delivering a visually striking   -
#-  and immersive experience.                                                 -
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------

[colors]
foreground    = "#000000"  # Negro puro (texto principal)
background    = "#ffffff"  # Blanco puro (fondo)
cursor_fg     = "#ffffff"  # Blanco puro (resaltado del cursor)
cursor_bg     = "#000000"  # Negro puro (relleno del cursor)
cursor_border = "#858585"  # Gris oscuro (borde del cursor)
selection_fg  = "#000000"  # Negro puro (texto seleccionado)
selection_bg  = "#d3d3d3"  # Gris claro (fondo de selección)

ansi = [
  "#ffffff",  # Blanco puro (fondo)
  "#ff0000",  # Rojo brillante (errores, advertencias críticas)
  "#008000",  # Verde medio (resaltado Git, agregado)
  "#606060",  # Gris oscuro (comentarios, elementos secundarios)
  "#a9a9a9",  # Gris claro (líneas de división, menos prominentes)
  "#000000",  # Negro puro (texto principal, destacados)
  "#d70000",  # Rojo oscuro (advertencias menos críticas, elementos de menor prioridad)
  "#000000"   # Negro puro (texto resaltado, alto contraste)
]

brights = [
  "#dcdcdc",  # Gris claro (fondo brillante, si aplica)
  "#ff3030",  # Rojo vibrante (cambios críticos, muy visible)
  "#00ff00",  # Verde brillante (confirmaciones exitosas, positivo)
  "#b0b0b0",  # Gris claro (bordes, elementos muy tenues)
  "#c0c0c0",  # Gris muy claro (separadores, menos visibles)
  "#000000",  # Negro puro (resaltado principal)
  "#858585",  # Gris oscuro (borde del cursor, elementos UI)
  "#303030"   # Gris oscuro (texto de alta visibilidad)
]

[metadata]
name = "Monochrome Light"
author = "Holairs"
